#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CodeHub.Views.Releases
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class ReleaseRazorView : ReleaseRazorViewBase
{

#line hidden

#line 1 "ReleaseRazorView.cshtml"
public ReleaseRazorViewModel Model { get; set; }

#line default
#line hidden


public override void Execute()
{
WriteLiteral("<html><head>\n<meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable" +
"=0\"");

WriteLiteral("/>\n<style>\n* {\nbox-sizing: border-box;\n}\nbody {\ncolor: #333;\nfont-family: Helveti" +
"ca, Arial, sans-serif;\nline-height: 1.42;\n}\nbody {\nfont-size: 15px;\nline-height:" +
" 1.7;\noverflow: hidden;\nword-wrap: break-word;\n}\nh1, h2, h3, h4, h5, h6 {\nmargin" +
": 1em 0 15px;\npadding: 0;\nfont-weight: bold;\nline-height: 1.7;\ncursor: text;\npos" +
"ition: relative;\n}\nh1 {\nfont-size: 1.8em;\nborder-bottom: 1px solid #ddd;\n}\n.mark" +
"down-body p, .markdown-body blockquote, .markdown-body ul, .markdown-body ol, .m" +
"arkdown-body dl, .markdown-body table, .markdown-body pre {\nmargin: 15px 0;\n}\n.m" +
"arkdown-body h2 {\nfont-size: 1.4em;\nborder-bottom: 1px solid #eee;\n}\n.markdown-b" +
"ody ul, .markdown-body ol {\npadding-left: 30px;\n}\na {\ncolor: #4183c4;\ntext-decor" +
"ation: none;\ntext-decoration: none;\n}\n.markdown-body .highlight pre, .markdown-b" +
"ody pre {\nbackground-color: #f8f8f8;\nborder: 1px solid #ddd;\nfont-size: 13px;\nli" +
"ne-height: 19px;\noverflow: auto;\npadding: 6px 10px;\nborder-radius: 3px;\n}\n.markd" +
"own-body pre {\nword-wrap: normal;\n}\n.markdown-body dl {\npadding: 0;\n}\n.markdown-" +
"body dl dt {\nfont-size: 14px;\nfont-weight: bold;\nfont-style: italic;\npadding: 0;" +
"\nmargin-top: 15px;\n}\n.markdown-body dl dd {\nmargin-bottom: 15px;\npadding: 0 15px" +
";\n}\n.markdown-body table {\nwidth: 100%;\noverflow: auto;\ndisplay: block;\n}\n.markd" +
"own-body table tr {\nborder-top: 1px solid #ccc;\nbackground-color: #fff;\n}\n.markd" +
"own-body table tr:nth-child(2n) {\nbackground-color: #f8f8f8;\n}\n.markdown-body ta" +
"ble th, .markdown-body table td {\nborder: 1px solid #ddd;\npadding: 6px 13px;\n}\n." +
"markdown-body table th {\nfont-weight: bold;\n}\n.markdown-body img {\nmax-width: 10" +
"0%;\n-moz-box-sizing: border-box;\nbox-sizing: border-box;\n}\n.release-authorship {" +
"\n\tmargin-top: 5px;\n\tmargin-bottom: 20px;\n\tfont-size: 14px;\n\tcolor: #999;\n}\n.rele" +
"ase-authorship img.avatar {\ndisplay: inline-block;\noverflow: hidden;\nline-height" +
": 1;\nvertical-align: middle;\nborder-radius: 3px;\n}\n.release-authorship span {\nfo" +
"nt-weight: bold;\ncolor: #666;\n}\n\n</style>\n<title>Release</title></head>\n<body>\n\t" +
"<h1>");


#line 117 "ReleaseRazorView.cshtml"
Write(Model.Name);


#line default
#line hidden
WriteLiteral("</h1>\n\t<p");

WriteLiteral(" class=\"release-authorship\"");

WriteLiteral(">\n\t\t<img");

WriteLiteral(" class=\"avatar\"");

WriteLiteral(" height=\"20\"");

WriteAttribute ("src", " src=\"", "\""

#line 119 "ReleaseRazorView.cshtml"
 , Tuple.Create<string,object,bool> ("", Model.AuthorAvatarUrl

#line default
#line hidden
, false)
);
WriteLiteral(" width=\"20\"");

WriteLiteral(">\n\t\t<span>");


#line 120 "ReleaseRazorView.cshtml"
   Write(Model.Author);


#line default
#line hidden
WriteLiteral("</span>\n\t\treleased this\n\t\t<time>");


#line 122 "ReleaseRazorView.cshtml"
   Write(Model.ReleaseTime);


#line default
#line hidden
WriteLiteral("</time>\n\t</p>\n\t<div");

WriteLiteral(" class=\"markdown-body\"");

WriteLiteral(">\n");

WriteLiteral("\t\t");


#line 125 "ReleaseRazorView.cshtml"
WriteLiteral(Model.Body);


#line default
#line hidden
WriteLiteral("\n\t</div>\n</body>\n</html>");

}
}

// NOTE: this is the default generated helper class. You may choose to extract it to a separate file 
// in order to customize it or share it between multiple templates, and specify the template's base 
// class via the @inherits directive.
public abstract class ReleaseRazorViewBase
{

		// This field is OPTIONAL, but used by the default implementation of Generate, Write, WriteAttribute and WriteLiteral
		//
		System.IO.TextWriter __razor_writer;

		// This method is OPTIONAL
		//
		/// <summary>Executes the template and returns the output as a string.</summary>
		/// <returns>The template output.</returns>
		public string GenerateString ()
		{
			using (var sw = new System.IO.StringWriter ()) {
				Generate (sw);
				return sw.ToString ();
			}
		}

		// This method is OPTIONAL, you may choose to implement Write and WriteLiteral without use of __razor_writer
		// and provide another means of invoking Execute.
		//
		/// <summary>Executes the template, writing to the provided text writer.</summary>
		/// <param name="writer">The TextWriter to which to write the template output.</param>
		public void Generate (System.IO.TextWriter writer)
		{
			__razor_writer = writer;
			Execute ();
			__razor_writer = null;
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the template output without HTML escaping it.</summary>
		/// <param name="value">The literal value.</param>
		protected void WriteLiteral (string value)
		{
			__razor_writer.Write (value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the TextWriter without HTML escaping it.</summary>
		/// <param name="writer">The TextWriter to which to write the literal.</param>
		/// <param name="value">The literal value.</param>
		protected static void WriteLiteralTo (System.IO.TextWriter writer, string value)
		{
			writer.Write (value);
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a value to the template output, HTML escaping it if necessary.</summary>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected void Write (object value)
		{
			WriteTo (__razor_writer, value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes an object value to the TextWriter, HTML escaping it if necessary.</summary>
		/// <param name="writer">The TextWriter to which to write the value.</param>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected static void WriteTo (System.IO.TextWriter writer, object value)
		{
			if (value == null)
				return;

			var write = value as Action<System.IO.TextWriter>;
			if (write != null) {
				write (writer);
				return;
			}

			//NOTE: a more sophisticated implementation would write safe and pre-escaped values directly to the
			//instead of double-escaping. See System.Web.IHtmlString in ASP.NET 4.0 for an example of this.
			writer.Write(System.Net.WebUtility.HtmlEncode (value.ToString ()));
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to the template output.
		/// </summary>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		protected void WriteAttribute (string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			WriteAttributeTo (__razor_writer, name, prefix, suffix, values);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to a TextWriter.
		/// </summary>
		/// <param name="writer">The TextWriter to which to write the attribute.</param>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		///<remarks>Used by Razor helpers to write attributes.</remarks>
		protected static void WriteAttributeTo (System.IO.TextWriter writer, string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			// this is based on System.Web.WebPages.WebPageExecutingBase
			// Copyright (c) Microsoft Open Technologies, Inc.
			// Licensed under the Apache License, Version 2.0
			if (values.Length == 0) {
				// Explicitly empty attribute, so write the prefix and suffix
				writer.Write (prefix);
				writer.Write (suffix);
				return;
			}

			bool first = true;
			bool wroteSomething = false;

			for (int i = 0; i < values.Length; i++) {
				Tuple<string,object,bool> attrVal = values [i];
				string attPrefix = attrVal.Item1;
				object value = attrVal.Item2;
				bool isLiteral = attrVal.Item3;

				if (value == null) {
					// Nothing to write
					continue;
				}

				// The special cases here are that the value we're writing might already be a string, or that the 
				// value might be a bool. If the value is the bool 'true' we want to write the attribute name instead
				// of the string 'true'. If the value is the bool 'false' we don't want to write anything.
				//
				// Otherwise the value is another object (perhaps an IHtmlString), and we'll ask it to format itself.
				string stringValue;
				bool? boolValue = value as bool?;
				if (boolValue == true) {
					stringValue = name;
				} else if (boolValue == false) {
					continue;
				} else {
					stringValue = value as string;
				}

				if (first) {
					writer.Write (prefix);
					first = false;
				} else {
					writer.Write (attPrefix);
				}

				if (isLiteral) {
					writer.Write (stringValue ?? value);
				} else {
					WriteTo (writer, stringValue ?? value);
				}
				wroteSomething = true;
			}
			if (wroteSomething) {
				writer.Write (suffix);
			}
		}
		// This method is REQUIRED. The generated Razor subclass will override it with the generated code.
		//
		///<summary>Executes the template, writing output to the Write and WriteLiteral methods.</summary>.
		///<remarks>Not intended to be called directly. Call the Generate method instead.</remarks>
		public abstract void Execute ();

}
}
#pragma warning restore 1591
