#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeHub.WebViews
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class UpgradeDetailsWebView : UpgradeDetailsWebViewBase
{

#line hidden

#line 1 "UpgradeDetailsWebView.cshtml"
public UpgradeDetailsModel Model { get; set; }

#line default
#line hidden


public override void Execute()
{
WriteLiteral("<html><head>\n<meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable" +
"=0\"");

WriteLiteral("/>\n<style>\n* {\n    box-sizing: border-box;\n}\nhtml {\n    -webkit-text-size-adjust:" +
" none;\n}\nbody {\n    color: #333;\n    font-family: Helvetica, Arial, sans-serif;\n" +
"    line-height: 1.42;\n    font-size: 16px;\n    line-height: 1.7;\n    word-wrap:" +
" break-word;\n}\nh1,\nh2,\nh3,\nh4,\nh5,\nh6 {\n    margin: 1em 0 15px;\n    padding: 0;\n" +
"    font-weight: bold;\n    line-height: 1.7;\n    cursor: text;\n    position: rel" +
"ative;\n}\nh1 {\n    font-size: 1.8em;\n    border-bottom: 1px solid #ddd;\n}\np,\nbloc" +
"kquote,\nul,\nol,\ndl,\ntable,\npre {\n    margin: 15px 0;\n}\nh2 {\n    font-size: 1.4em" +
";\n    border-bottom: 1px solid #eee;\n}\nul,\nol {\n    padding-left: 20px;\n}\na {\n  " +
"  color: #4183c4;\n    text-decoration: none;\n    text-decoration: none;\n}\n.highl" +
"ight pre,\npre {\n    background-color: #f8f8f8;\n    border: 1px solid #ddd;\n    l" +
"ine-height: 19px;\n    overflow: auto;\n    padding: 6px 10px;\n    border-radius: " +
"3px;\n}\npre {\n    word-wrap: normal;\n}\ndl {\n    padding: 0;\n}\ndl dt {\n    font-we" +
"ight: bold;\n    font-style: italic;\n    padding: 0;\n    margin-top: 15px;\n}\ndl d" +
"d {\n    margin-bottom: 15px;\n    padding: 0 15px;\n}\ntable {\n    width: 100%;\n   " +
" overflow: auto;\n    display: block;\n}\ntable tr {\n    border-top: 1px solid #ccc" +
";\n    background-color: #fff;\n}\ntable tr:nth-child(2n) {\n    background-color: #" +
"f8f8f8;\n}\ntable th,\ntable td {\n    border: 1px solid #ddd;\n    padding: 6px 13px" +
";\n}\ntable th {\n    font-weight: bold;\n}\nimg {\n    max-width: 100%;\n    -moz-box-" +
"sizing: border-box;\n    box-sizing: border-box;\n}\nul.task-list > li.task-list-it" +
"em {\n    list-style-type: none;\n}\n.task-list-item-checkbox {\n    margin-left: -2" +
"0px;\n    vertical-align: middle;\n}\n.btn {\n    margin-top: 1.50em;\n    margin-bot" +
"tom: 1em;\n    padding: 1em 2em;\n    text-align: center;\n    display: inline-bloc" +
"k;\n    border-radius: 15px;\n    border: none;\n    transform: translateY(1px);\n  " +
"  color: #fff;\n}\n#buy {\n    background-color: #2ecc71;\n    box-shadow: 0 3px #27" +
"ae60;\n}\n#purchased {\n    background-color: #34495e;\n    box-shadow: 0 3px #2c3e5" +
"0;\n}\n");

WriteLiteral(@"@media (max-width: 640px) {
    .btn,
    #restore {
        display: block;
    }
    #restore {
        text-align: center;
    }
}
</style>
    <title>Pro Version</title>
</head>
<body>
    <p>
        <b>CodeHub Pro</b> gives you access the all the great features below:
    </p>

    <ul>
        <li><a");

WriteLiteral(" href=\"#private\"");

WriteLiteral(">Private Repositories</a></li>\n        <li><a");

WriteLiteral(" href=\"#enterprise\"");

WriteLiteral(">Enterprise Support</a></li>\n        <li><a");

WriteLiteral(" href=\"#push\"");

WriteLiteral(">Push Notifications</a></li>\n    </ul>\n\n    <p>\n        Before you buy please tak" +
"e a look at the detailed description for each feature below. \n        If you\'re " +
"unsure about any aspect of the Pro version, please feel free to \n        <a");

WriteLiteral(" href=\"mailto:codehubapp@gmail.com?Subject=CodeHub%20Pro%20Question\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">contact me</a>!\n    </p>\n\n");


#line 163 "UpgradeDetailsWebView.cshtml"
    

#line default
#line hidden

#line 163 "UpgradeDetailsWebView.cshtml"
     if (Model.IsPurchased)
    {


#line default
#line hidden
WriteLiteral("        <p>\n            <a");

WriteLiteral(" id=\"purchased\"");

WriteLiteral(" class=\"btn\"");

WriteLiteral(">Pro Already Enabled!</a>\n        </p>\n");


#line 168 "UpgradeDetailsWebView.cshtml"
    }
    else
    {
        if (Model.Price != null)
        {


#line default
#line hidden
WriteLiteral("            <p>\n                <a");

WriteLiteral(" id=\"buy\"");

WriteLiteral(" href=\"app://buy\"");

WriteLiteral(" class=\"btn\"");

WriteLiteral(">Purchase CodeHub Pro for ");


#line 174 "UpgradeDetailsWebView.cshtml"
                                                                             Write(Model.Price);


#line default
#line hidden
WriteLiteral("</a>\n            </p>\n");

WriteLiteral("            <p");

WriteLiteral(" id=\"restore\"");

WriteLiteral(">\n                <a");

WriteLiteral(" href=\"app://restore\"");

WriteLiteral(">Click here</a> to restore a previous purchase.\n            </p>\n");


#line 179 "UpgradeDetailsWebView.cshtml"
        }
    }


#line default
#line hidden
WriteLiteral("\n    <h2>Feature Details</h2>\n    <p>Below are the features that are available wh" +
"en purchasing CodeHub Pro.</p>\n\n    <h3");

WriteLiteral(" id=\"private\"");

WriteLiteral(@">Private Repositories</h3>
    <p>
        While CodeHub is free for all public projects, private repositories are only available with CodeHub Pro.
        The Pro edition allows access to all your private repositories and any private repositories any of your organizations have.
        Access to your private repositories is completely unrestricted. With CodeHub Pro, anything you are able to do with your open source repositories
        you are also capable of doing with your private repositories. Even more, access to private repositories, with CodeHub Pro, is applied to
        all your CodeHub accounts.
    </p>

    <h3");

WriteLiteral(" id=\"enterprise\"");

WriteLiteral(@">Enterprise Support</h3>
    <p>
        With CodeHub Pro, access to GitHub Enterprise instances becomes available for use. 
        Enterprise support allows for unlimited accounts, in CodeHub, accessing unlimited Enterprise instances - there are no restrictions!
        You can authenticate with your GitHub Enterprise instance in two ways: Basic Auth, or OAuth token. Unlike authentication
        with GitHub.com, there is no avilable web application flow, which means that you will be prompted for your credentials in a view that
        is native to CodeHub, not GitHub. This method, also known as Basic Auth, is safe. The username and password pair is <b>NOT</b> saved on the device
        nor is it ever sent anywhere but GitHub. Even more, the username and password is exchanged for an OAuth token on GitHub so you may revoke access
        at any time.
    </p>

    <p>
        If you feel unsafe authenticating with a username and password pair, you may choose to generate your own OAuth token on your enterprise instance and
        use it in CodeHub directly. This completely removes the need to type in your username and password within CodeHub. 
    </p>

    <h3");

WriteLiteral(" id=\"push\"");

WriteLiteral(">Push Notifications</h3>\n    <p><b>Note: Push Notifications are only available fo" +
"r GitHub.com accounts. Details below</b></p>\n\n    <img");

WriteLiteral(" width=\"400\"");

WriteLiteral(" src=\"http://codehub-app.com/assets/push-notification.png\"");

WriteLiteral(@" />

    <p>
        Push notifications allow you to take your typical GitHub notifications and push them directly to your mobile device.
        Users receive notifications for conversations in repositories they watch including:
    </p>

    <ul>
        <li>Issues and their comments</li>
        <li>Pull Requests and their comments</li>
        <li>Comments on any commits</li>
    </ul>

    <p>Notifications are also sent for conversations in unwatched repositories when the user is involved including:</p>

    <ul>
        <li>Mentions</li>
        <li>Issue assignments</li>
        <li>Commits the user authors or commits</li>
        <li>Any discussion in which the user actively participates</li>
    </ul>

    <p>
        Notifications are generated via a service owned and operated by Dillon Buchanan, creator of CodeHub. 
        These notifications are harvested from GitHub.com using a OAuth identification token generated just for 
        querying notifications on behalf of the user. This service, aptly called CodeHub-Push, is also open source and 
        <a");

WriteLiteral(" href=\"https://github.com/CodeHubApp/CodeHub-Push\"");

WriteLiteral(@">available for viewing on GitHub.</a>
    </p>
    <p>
        As mentioned above, push notifications are only available for GitHub.com accounts. Push notifications for 
        GitHub enterprise accounts are not available. This limitation is due to the fact that the notification service, 
        <a");

WriteLiteral(" href=\"https://github.com/CodeHubApp/CodeHub-Push\"");

WriteLiteral(@">CodeHub-Push</a>, cannot retrieve information from a enterprise
        instance. External access to a enterprise instance is almost always impossible due to network limitations as well as
        permission. For this reason, push notifications are unavailable for enterprise users - sorry.
    </p>
        
</body>
</html>");

}
}

// NOTE: this is the default generated helper class. You may choose to extract it to a separate file 
// in order to customize it or share it between multiple templates, and specify the template's base 
// class via the @inherits directive.
public abstract class UpgradeDetailsWebViewBase
{

		// This field is OPTIONAL, but used by the default implementation of Generate, Write, WriteAttribute and WriteLiteral
		//
		System.IO.TextWriter __razor_writer;

		// This method is OPTIONAL
		//
		/// <summary>Executes the template and returns the output as a string.</summary>
		/// <returns>The template output.</returns>
		public string GenerateString ()
		{
			using (var sw = new System.IO.StringWriter ()) {
				Generate (sw);
				return sw.ToString ();
			}
		}

		// This method is OPTIONAL, you may choose to implement Write and WriteLiteral without use of __razor_writer
		// and provide another means of invoking Execute.
		//
		/// <summary>Executes the template, writing to the provided text writer.</summary>
		/// <param name="writer">The TextWriter to which to write the template output.</param>
		public void Generate (System.IO.TextWriter writer)
		{
			__razor_writer = writer;
			Execute ();
			__razor_writer = null;
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the template output without HTML escaping it.</summary>
		/// <param name="value">The literal value.</param>
		protected void WriteLiteral (string value)
		{
			__razor_writer.Write (value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the TextWriter without HTML escaping it.</summary>
		/// <param name="writer">The TextWriter to which to write the literal.</param>
		/// <param name="value">The literal value.</param>
		protected static void WriteLiteralTo (System.IO.TextWriter writer, string value)
		{
			writer.Write (value);
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a value to the template output, HTML escaping it if necessary.</summary>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected void Write (object value)
		{
			WriteTo (__razor_writer, value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes an object value to the TextWriter, HTML escaping it if necessary.</summary>
		/// <param name="writer">The TextWriter to which to write the value.</param>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected static void WriteTo (System.IO.TextWriter writer, object value)
		{
			if (value == null)
				return;

			var write = value as Action<System.IO.TextWriter>;
			if (write != null) {
				write (writer);
				return;
			}

			//NOTE: a more sophisticated implementation would write safe and pre-escaped values directly to the
			//instead of double-escaping. See System.Web.IHtmlString in ASP.NET 4.0 for an example of this.
			writer.Write(System.Net.WebUtility.HtmlEncode (value.ToString ()));
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to the template output.
		/// </summary>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		protected void WriteAttribute (string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			WriteAttributeTo (__razor_writer, name, prefix, suffix, values);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to a TextWriter.
		/// </summary>
		/// <param name="writer">The TextWriter to which to write the attribute.</param>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		///<remarks>Used by Razor helpers to write attributes.</remarks>
		protected static void WriteAttributeTo (System.IO.TextWriter writer, string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			// this is based on System.Web.WebPages.WebPageExecutingBase
			// Copyright (c) Microsoft Open Technologies, Inc.
			// Licensed under the Apache License, Version 2.0
			if (values.Length == 0) {
				// Explicitly empty attribute, so write the prefix and suffix
				writer.Write (prefix);
				writer.Write (suffix);
				return;
			}

			bool first = true;
			bool wroteSomething = false;

			for (int i = 0; i < values.Length; i++) {
				Tuple<string,object,bool> attrVal = values [i];
				string attPrefix = attrVal.Item1;
				object value = attrVal.Item2;
				bool isLiteral = attrVal.Item3;

				if (value == null) {
					// Nothing to write
					continue;
				}

				// The special cases here are that the value we're writing might already be a string, or that the 
				// value might be a bool. If the value is the bool 'true' we want to write the attribute name instead
				// of the string 'true'. If the value is the bool 'false' we don't want to write anything.
				//
				// Otherwise the value is another object (perhaps an IHtmlString), and we'll ask it to format itself.
				string stringValue;
				bool? boolValue = value as bool?;
				if (boolValue == true) {
					stringValue = name;
				} else if (boolValue == false) {
					continue;
				} else {
					stringValue = value as string;
				}

				if (first) {
					writer.Write (prefix);
					first = false;
				} else {
					writer.Write (attPrefix);
				}

				if (isLiteral) {
					writer.Write (stringValue ?? value);
				} else {
					WriteTo (writer, stringValue ?? value);
				}
				wroteSomething = true;
			}
			if (wroteSomething) {
				writer.Write (suffix);
			}
		}
		// This method is REQUIRED. The generated Razor subclass will override it with the generated code.
		//
		///<summary>Executes the template, writing output to the Write and WriteLiteral methods.</summary>.
		///<remarks>Not intended to be called directly. Call the Generate method instead.</remarks>
		public abstract void Execute ();

}
}
#pragma warning restore 1591
